Server:
  IP: 0.0.0.0
  Port: 50053
  AccessToken: "1234567890qwertyuiop"
Log:
  Level: "info"
  LogPath: "runtimes/logs/app.log"
chat:
  api_key: "i0jey84SdkFdw5u43780yjr3h7se8nth0yi295nr94ksDngKprEh"
  base_url: "http://192.168.88.135:8084/v1"
  model: "gpt-3.5-turbo"
  max_tokens: 4096
  temperature: 0.8
  top_p: 0.9
  frequency_penalty: 0.8
  presence_penalty: 0.5
  bit_desc: "你是一个ai助手，我需要你模拟一名软件工程师来回答我的问题"
  min_response_tokens: 2048
  context_ttl: 1800
  context_len: 4

